### PR TITLE
Testing folder reorg

### PR DESCRIPTION
**Pull request by WyattMufson**
I refactored the testing folders:
- Moved everything into a folder name `ontology_test`
- Named all files `test_${TESTNAME}`
- Removed duplicate `runall.bash` and `Makefile` files
- Added the `-t` flag to `run.py` to return whether a file compiled successfully and delete the accompanying files
- Modified `runall.py` so that it prints out the amount of files that compile successfully (for example now it prints `60/60 Tests Passed` at the end.
- `runall.py` returns `1` if all tests pass and `0` if not. Can hook this up to a CI.

### CODE REVIEW

**Comment by carltraveler** [comment]
thanks for this commit. however about the test, it's useless for all of this test only passed for compile ok to assure the correctless. currently I seperate it with comunication with chain or not. it's convenient local test. if you need this commit. I think currently you can leave it as a local branch.

**Comment by WyattMufson** [comment]
@carltraveler I think this isn't useless. It's a good first step to having the repo be tested. The `testdata` folder is unorganized and needs clarity. I'm trying to make this resemble the https://github.com/CityOfZion/neo-boa/tree/master/boa_test folder.

What I'll do is put all of the current tests into an `example` folder within `ontology_test` and change the current script to say `60/60 Files Compiles Correctly`. Then we can add actual tests in a tests folder within `ontology_test`.

**Comment by WyattMufson** [comment]
@carltraveler I think this PR will greatly improve readability and organization of this project. It's not meant to be considered that the whole repo is being fully tested - only that it is in a better position to be tested in the future. I think this is ready to be merged in.

**Comment by WyattMufson** [comment]
@carltraveler any other comments on this?

**Comment by carltraveler** [comment]
@WyattMufson ok, I agree this will improve the readability. and can you leave the runall.bash seperately? I use it usually.

**Comment by WyattMufson** [comment]
@carltraveler I just saw your response. I re-added the original `runall.bash` file. I'm going to go ahead and merge this in.

**Pull request merged**
